/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DeadLink (https://sketchfab.com/d43dLink)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-setup-8a75c64542c14be0ad3dcf75423eda0d
Title: Gaming Setup
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

const PC = (props) => {
  const { nodes, materials } = useGLTF('/models/gaming_setup.glb');

  const monitorTexture = useTexture('textures/desk/monitor.png')

  const screenTexture = useTexture('/textures/desk/screen.png')

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stoo1_Stoo1_0.geometry}
          material={materials.Stoo1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sit_sit_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pc_pc_0.geometry}
          material={materials.material_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pc_pc_0_1.geometry}
          material={materials.material_2}
        />
      </group>
    </group>
  )
}

export default PC;

useGLTF.preload('/models/gaming_setup.glb')
